name: Build Client EXE

on:
  push:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # Use a valid Python version
        check-latest: true

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller

    # Step 4: Build the EXE
    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --noconsole client/client.py

    # Step 5: Upload the EXE as an artifact
    - name: Upload Client EXE
      uses: actions/upload-artifact@v3
      with:
        name: client-exe
        path: dist/client.exe
