name: Build Client EXE

on:
  push:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install Python 3.1
    - name: Install Python 3.1
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget zlib1g-dev
        wget https://www.python.org/ftp/python/3.1.5/Python-3.1.5.tgz
        tar -xvzf Python-3.1.5.tgz
        cd Python-3.1.5
        ./configure
        make
        sudo make install
        python3.1 --version

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python3.1 -m ensurepip --upgrade
        python3.1 -m pip install --upgrade pip
        python3.1 -m pip install pyinstaller

    # Step 4: Build the EXE
    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --noconsole client/client.py

    # Step 5: Upload the EXE as an artifact
    - name: Upload Client EXE
      uses: actions/upload-artifact@v3
      with:
        name: client-exe
        path: dist/client.exe
